In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
df = files.upload()

Saving SY 2023-2024 School Level Data on Official Enrollment 13.xlsx to SY 2023-2024 School Level Data on Official Enrollment 13.xlsx

In [ ]:
df = pd.read_csv('/content/deped_enrollment.csv', dtype={'beis_school_id': str})

FileNotFoundError: [Errno 2] No such file or directory: '/content/deped_enrollment.csv'

In [ ]:
df.head()

AttributeError: 'dict' object has no attribute 'head'

In [ ]:
# Remove metadata (info title) rows, set header, drop header row, and reset index
df_cleaned = df.iloc[3:].reset_index(drop=True)
df_cleaned.columns = df_cleaned.iloc[0]
df_cleaned = df_cleaned[1:].reset_index(drop=True)


# Drop columns and rows that are completely empty (all NaN)
df_cleaned = df_cleaned.dropna(axis=1, how='all')
df_cleaned = df_cleaned.dropna(how='all')

In [ ]:
# Convert column names to lowercase and replace spaces with underscores
df_cleaned.columns = df_cleaned.columns.str.lower().str.replace(" ", "_")

In [ ]:
# Display
df_cleaned.head()

,region,division,district,beis_school_id,school_name,street_address,province,municipality,legislative_district,barangay,...,g12_acad_gas_male,g12_acad_gas_female,g12_acad_pbm_male,g12_acad_pbm_female,g12_tvl_male,g12_tvl_female,g12_sports_male,g12_sports_female,g12_arts_male,g12_arts_female
0,Region I,Ilocos Norte,Bacarra I,100001,Apaleng-Libtong ES,"Brgy. 21, Libtong, Bacarra, Ilocos Norte",ILOCOS NORTE,BACARRA,1st District,LIBTONG,...,0,0,0,0,0,0,0,0,0,0
1,Region I,Ilocos Norte,Bacarra I,100002,Bacarra CES,Santa Rita,ILOCOS NORTE,BACARRA,1st District,SANTA RITA (POB.),...,0,0,0,0,0,0,0,0,0,0
2,Region I,Ilocos Norte,Bacarra I,100003,Buyon ES,NONE,ILOCOS NORTE,BACARRA,1st District,BUYON,...,0,0,0,0,0,0,0,0,0,0
3,Region I,Ilocos Norte,Bacarra I,100004,Ganagan Elementary School,"#37 Ganagan,Bacarra, Ilocos Norte",ILOCOS NORTE,BACARRA,1st District,GANAGAN,...,0,0,0,0,0,0,0,0,0,0
4,Region I,Ilocos Norte,Bacarra I,100005,Macupit ES,Macupit,ILOCOS NORTE,BACARRA,1st District,MACUPIT,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Check if may NaN
df_cleaned.isna().any().any()

np.True_

In [ ]:
# Calculate the total number of NaN
df_cleaned.isna().sum().sum()

np.int64(1752)

In [ ]:
# Print NaN counts for columns with missing values
nan_counts = df_cleaned.isna().sum()
print(nan_counts[nan_counts > 0])

0
street_address    1682
barangay            70
dtype: int64

In [ ]:
# Display rows with at least one NaN value
df_cleaned[df_cleaned.isna().any(axis=1)]

,region,division,district,beis_school_id,school_name,street_address,province,municipality,legislative_district,barangay,...,g12_acad_gas_male,g12_acad_gas_female,g12_acad_pbm_male,g12_acad_pbm_female,g12_tvl_male,g12_tvl_female,g12_sports_male,g12_sports_female,g12_arts_male,g12_arts_female
27,Region I,Ilocos Norte,Bacarra II,100023,Tubburan ES,NaN,ILOCOS NORTE,BACARRA,1st District,TUBBURAN,...,0,0,0,0,0,0,0,0,0,0
57,Region I,Ilocos Norte,Bangui,100043,Abaca Elementary School,NaN,ILOCOS NORTE,BANGUI,1st District,ABACA,...,0,0,0,0,0,0,0,0,0,0
59,Region I,Ilocos Norte,Bangui,100045,Bacsil ES,NaN,ILOCOS NORTE,BANGUI,1st District,BACSIL,...,0,0,0,0,0,0,0,0,0,0
67,Region I,Ilocos Norte,Bangui,100053,Nagbalagan ES,NaN,ILOCOS NORTE,BANGUI,1st District,NAGBALAGAN,...,0,0,0,0,0,0,0,0,0,0
68,Region I,Ilocos Norte,Bangui,100054,Paddagan ES,NaN,ILOCOS NORTE,BANGUI,1st District,PAYAC,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60162,PSO,Italy,Lazio,700034,International Philippine School in Italy,"Via Onofrio Panvinio, 11, 00162 Rome, Italy",NCR SECOND DISTRICT,CITY OF PASIG,Lone District,NaN,...,0,0,0,0,0,0,0,0,0,0
60163,PSO,Sultanate of Oman,Muscat,700026,Philippine School,4277 Way 2740 AlKhuwair,NCR SECOND DISTRICT,CITY OF PASIG,Lone District,NaN,...,0,0,0,0,0,0,0,0,0,0
60164,PSO,State of Kuwait,Jleeb Al-Shuyoukh,700027,The New Kuwait-Philippines International School,Block 1 Jleeb Al-Shuyoukh,NCR SECOND DISTRICT,CITY OF PASIG,Lone District,NaN,...,0,0,0,0,0,0,0,0,0,0
60165,PSO,State of Kuwait,Fahaheel,700030,Philippine International English School,Block 11 Street 54 Fahaheel,NCR SECOND DISTRICT,CITY OF PASIG,Lone District,NaN,...,1,0,0,0,0,0,0,0,0,0
60166,PSO,Greece,Athens,700031,Philippine School in Greece,"Thimaton Polemou 15 Kareas,Vyronas",NCR SECOND DISTRICT,CITY OF PASIG,Lone District,NaN,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Hindi na ako nag drop ng NaN kasi 0.04 lang naman 'yong missing T.T
# Nag fill nalang ako ng "Not provided"
df_cleaned['street_address'] = df_cleaned['street_address'].fillna("Not provided")
df_cleaned['barangay'] = df_cleaned['barangay'].fillna("Not provided")

In [ ]:
# Count duplicates
df.duplicated().sum()

np.int64(0)

In [ ]:
# Check if may NaN
df_cleaned.isna().any().any()

np.False_

In [ ]:
# To save the file ( sa vscode lang to gumagana, wag na i-run)
df_cleaned.to_csv("cleaned_data.csv", index=False)

In [ ]:
import re

# Clean the street address column
def clean_street_address(address):
    if not isinstance(address, str):
        return "Not provided"

    address = address.strip()  # Remove extra spaces

    # Unexpected characters
    address = address.replace('"', '').replace("'", "").strip()

    # Define invalid values to replace with "Not provided"
    missing_values = {"0", "0.0", "not applicable", "Not Applicable",
                      "not available", "Not Available", "-none",
                      "none", "n/a", "N/A", "N / A", "n / a",
                      "_ _ _ _", "______", "-----", "------"}

    if address.lower() in missing_values:
        return "Not provided"

    # If the value is just multiple zeroes, replace it
    if re.fullmatch(r"0+", address):
        return "Not provided"

    # Remove leading "- ", "_", "*", ",", or "." if present
    address = re.sub(r"^[\s,._-]+", "", address)

    # Fix "@nd" → "2nd"
    address = re.sub(r"@nd", "2nd", address, flags=re.IGNORECASE)

    # If less than 5 characters after cleaning, set to "Not provided"
    if len(address) < 5:
        return "Not provided"

    return address

# Apply function to street_address column
df_cleaned['street_address'] = df_cleaned['street_address'].apply(clean_street_address)

# Extra forced replacement for any remaining quoted "0", "N/A", or "None"
df_cleaned['street_address'] = df_cleaned['street_address'].replace(
    to_replace=r'^\s*["\']?(0+|N/A|None|none|n/a|not available|not applicable)["\']?\s*$',
    value="Not provided",
    regex=True
)

In [ ]:
# Count 0s
zero_values_count = (df_cleaned['street_address'] == "0").sum()

print(f'Number of "0" values in street_address: {zero_values_count}')

Number of "0" values in street_address: 0

In [ ]:
# Trim spaces that are double, trailing, and leading
def trim_whitespace(value):
    if isinstance(value, str):
        return " ".join(value.split())
    return value

# Columns 1 to 14
df_cleaned.iloc[:, 0:14] = df_cleaned.iloc[:, 0:14].apply(lambda col: col.apply(trim_whitespace) if col.dtype == "object" else col)

In [ ]:
# Consistent format in division column
def clean_division(value):
    if isinstance(value, str):
        if value.lower().startswith("city of "):
            return value[8:] + " City"

        # Fix Lanao del Sur - I, inconsistent formart
        if " - " in value:
            value = value.replace(" - ", " ")

        # To match format with other Samar regions
        if value.lower() == "samar (western samar)":
            return "Western Samar"

    return value

In [ ]:
df_cleaned['division'] = df_cleaned['division'].apply(clean_division)

In [ ]:
# Remove spaces around hyphens in district names
def clean_district(value):
    if isinstance(value, str):
        value = value.strip()
        value = value.replace(" - ", "-")
    return value

In [ ]:
df_cleaned['district'] = df_cleaned['district'].apply(clean_district)

In [ ]:
import re

# Function to properly capitalize each word, including after hyphens and parentheses
def capitalize_properly(value):
    if isinstance(value, str):

        return re.sub(r"(\b[a-z])|(?<=\(|-)[a-z]", lambda x: x.group().upper(), value.lower())
    return value

In [ ]:
# Apply function to province, municipality, and barangay columns
df_cleaned['province'] = df_cleaned['province'].apply(capitalize_properly)
df_cleaned['municipality'] = df_cleaned['municipality'].apply(capitalize_properly)
df_cleaned['barangay'] = df_cleaned['barangay'].apply(capitalize_properly)

In [ ]:
df_cleaned.head()

,region,division,district,beis_school_id,school_name,street_address,province,municipality,legislative_district,barangay,...,g12_acad_gas_male,g12_acad_gas_female,g12_acad_pbm_male,g12_acad_pbm_female,g12_tvl_male,g12_tvl_female,g12_sports_male,g12_sports_female,g12_arts_male,g12_arts_female
0,Region I,Ilocos Norte,Bacarra I,100001,Apaleng-Libtong ES,"Brgy. 21, Libtong, Bacarra, Ilocos Norte",Ilocos Norte,Bacarra,1st District,Libtong,...,0,0,0,0,0,0,0,0,0,0
1,Region I,Ilocos Norte,Bacarra I,100002,Bacarra CES,Santa Rita,Ilocos Norte,Bacarra,1st District,Santa Rita (Pob.),...,0,0,0,0,0,0,0,0,0,0
2,Region I,Ilocos Norte,Bacarra I,100003,Buyon ES,Not provided,Ilocos Norte,Bacarra,1st District,Buyon,...,0,0,0,0,0,0,0,0,0,0
3,Region I,Ilocos Norte,Bacarra I,100004,Ganagan Elementary School,"#37 Ganagan,Bacarra, Ilocos Norte",Ilocos Norte,Bacarra,1st District,Ganagan,...,0,0,0,0,0,0,0,0,0,0
4,Region I,Ilocos Norte,Bacarra I,100005,Macupit ES,Macupit,Ilocos Norte,Bacarra,1st District,Macupit,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df_cleaned.to_csv("cleaned_data.csv", index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df_cleaned.to_csv("/content/drive/My Drive/cleaned_data.csv", index=False, encoding='utf-8')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [ ]:
missing_ids = df_cleaned['beis_school_id'].isna().sum()
print(f"Missing BEIS School IDs: {missing_ids}")

Missing BEIS School IDs: 0

In [ ]:
# Check if may NaN
df_cleaned.isna().any().any()

np.False_